version: '3.8'

services:
  # ================================
  # Base de Datos PostgreSQL (Desarrollo)
  # ================================
  postgres-dev:
    image: postgres:15-alpine
    container_name: ecommerce-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommerce_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - ecommerce-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ================================
  # Aplicación en modo desarrollo
  # ================================
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: ecommerce-app-dev
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres-dev:5432/ecommerce_dev
      JWT_SECRET: jwt-secret-desarrollo
      JWT_EXPIRES_IN: 7d
      PORT: 3000
      NODE_ENV: development
      LOG_LEVEL: debug
      LOG_DIR: ./logs
      THROTTLE_TTL: 60
      THROTTLE_LIMIT: 100
      SYNC_PRODUCTS_CRON: "0 */12 * * *"
      DUMMYJSON_API_URL: https://dummyjson.com
    ports:
      - "3000:3000"
      - "9229:9229" # Puerto para debugging
    volumes:
      - .:/app
      - /app/node_modules
      - dev_logs:/app/logs
    networks:
      - ecommerce-dev-network
    depends_on:
      postgres-dev:
        condition: service_healthy
    command: >
      sh -c "
        npm install &&
        npx prisma migrate dev &&
        npx prisma generate &&
        npm run start:dev
      "

  # ================================
  # Redis para desarrollo
  # ================================
  redis-dev:
    image: redis:7-alpine
    container_name: ecommerce-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ecommerce-dev-network

volumes:
  postgres_dev_data:
    driver: local
    name: ecommerce_postgres_dev_data
  
  dev_logs:
    driver: local
    name: ecommerce_dev_logs

networks:
  ecommerce-dev-network:
    driver: bridge
    name: ecommerce_dev_network
